import React, { useState } from 'react';
import { RecoveryNode, RecoveryPlan } from '../types';
import { 
  X, 
  Copy, 
  Check, 
  Download, 
  Edit3, 
  Sparkles, 
  FileText, 
  Printer, 
  RefreshCw 
} from 'lucide-react';

interface AIApplicationGeneratorModalProps {
  node: RecoveryNode;
  plan: RecoveryPlan;
  onClose: () => void;
}

export const AIApplicationGeneratorModal: React.FC<AIApplicationGeneratorModalProps> = ({
  node,
  plan,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const defaultDraft = `FORMAL ADMINISTRATIVE ACCESS RESTORATION APPLICATION
Generated by RE:START AI Life-Admin Recovery Engine

Date: ${new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' })}

TO:
The Concerned Authority / Branch In-Charge
${node.portalOrAuthority}

SUBJECT: URGENT: Request for priority duplicate credential reissuance & service restoration - ${node.title}

Respected Officer,

I am writing to formally report an unforeseen disruption of my essential identity and financial access and to request immediate administrative restoration under regulatory priority guidelines.

1. APPLICANT & INCIDENT SUMMARY:
   - Primary Incident: Stolen travel belongings including primary mobile device, physical identity documents, and banking credentials.
   - User Reference: ${plan.userPersona?.name || 'Applicant'} (${plan.userPersona?.age || 24} yrs)
   - Disruption Description: "${plan.situation}"
   - Requested Action: ${node.title}

2. STATUTORY & VERIFICATION COMPLIANCE:
   - Defensive Steps Taken: All compromised payment instruments and cards have been frozen via automated IVR.
   - Statutory Report: Official Police Lost Property e-Report acknowledgement has been registered.
   - Digital Identity: Certified digitally signed e-credentials (DigiLocker UIDAI / PAN) are attached for instantaneous biometric e-KYC matching.

3. REMEDY REQUESTED:
   In light of an urgent salary deposit and essential recurring obligations, I respectfully request your office to:
   a. Process the reissuance / reset of the above-mentioned credential without requiring physical plastic cards that were lost in the incident.
   b. Waive unauthorized liability during the period between incident occurrence and official report submission.
   c. Issue an official stamp/slip confirming completion of this recovery stage.

Yours sincerely,

[Applicant Signature]
Name: ${plan.userPersona?.name || 'Rohan'}
Contact: [Temporary / Restored Mobile Contact]

SUPPORTING ATTACHMENTS ATTESTED:
1. Certified DigiLocker e-Identity Document
2. Official Police Loss Report Acknowledgement (LRN)
3. Employer Salary Verification Letter`;

  const [draftContent, setDraftContent] = useState(defaultDraft);

  const handleCopy = () => {
    navigator.clipboard.writeText(draftContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([draftContent], { type: 'text/plain;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = `RESTART_Application_${node.category}_${Date.now()}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>RE:START Official Application Draft</title>
            <style>
              body { font-family: monospace; white-space: pre-wrap; padding: 40px; font-size: 13px; line-height: 1.6; }
            </style>
          </head>
          <body>${draftContent}</body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
    }
  };

  const handleRegenerate = async () => {
    setIsGenerating(true);
    try {
      const res = await fetch('/api/recovery/generate-application', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          templateType: node.draftTemplateType || 'general',
          planTitle: plan.title,
          situation: plan.situation,
          nodeTitle: node.title,
          authority: node.portalOrAuthority,
        }),
      });
      const data = await res.json();
      if (data.content) {
        setDraftContent(data.content);
      }
    } catch (e) {
      console.warn('Draft regeneration failed, using local model:', e);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-xl animate-in fade-in duration-200">
      <div className="relative w-full max-w-3xl glass-panel-highlight rounded-3xl border border-white/20 shadow-2xl p-6 sm:p-8 max-h-[90vh] flex flex-col justify-between overflow-hidden">
        {/* Header */}
        <div className="flex items-start justify-between gap-4 pb-4 border-b border-white/10">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-cyan-500/20 border border-cyan-500/30 text-cyan-300">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-[11px] font-semibold text-cyan-400 uppercase tracking-wider">
                  Official Application Assistant
                </span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-white/10 text-neutral-300 font-mono">
                  Ready to Submit
                </span>
              </div>
              <h3 className="text-lg sm:text-xl font-bold text-white leading-tight">
                {node.title} — Request Letter
              </h3>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-neutral-400 hover:text-white bg-white/5 hover:bg-white/10 border border-white/10 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Box / Editor */}
        <div className="my-4 flex-1 overflow-y-auto">
          {isEditing ? (
            <textarea
              value={draftContent}
              onChange={(e) => setDraftContent(e.target.value)}
              className="w-full h-80 bg-black/60 border border-cyan-500/40 rounded-2xl p-4 font-mono text-xs text-neutral-100 focus:outline-none focus:ring-1 focus:ring-cyan-400 leading-relaxed resize-none"
            />
          ) : (
            <div className="bg-black/50 border border-white/10 rounded-2xl p-5 font-mono text-xs text-neutral-300 whitespace-pre-wrap leading-relaxed max-h-[360px] overflow-y-auto selection:bg-cyan-500/30">
              {draftContent}
            </div>
          )}
        </div>

        {/* Toolbar & Actions */}
        <div className="pt-4 border-t border-white/10 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsEditing(!isEditing)}
              className={`px-3 py-1.5 rounded-xl text-xs font-medium border flex items-center gap-1.5 transition-all ${
                isEditing
                  ? 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40'
                  : 'bg-white/5 text-neutral-300 border-white/10 hover:bg-white/10 hover:text-white'
              }`}
            >
              <Edit3 className="w-3.5 h-3.5" />
              <span>{isEditing ? 'Done Editing' : 'Edit Text'}</span>
            </button>

            <button
              onClick={handleRegenerate}
              disabled={isGenerating}
              className="px-3 py-1.5 rounded-xl text-xs font-medium bg-white/5 hover:bg-white/10 border border-white/10 text-neutral-300 hover:text-white flex items-center gap-1.5 transition-all"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${isGenerating ? 'animate-spin' : ''}`} />
              <span>Regenerate with Gemini</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 rounded-xl text-xs font-medium bg-white/5 hover:bg-white/10 border border-white/10 text-neutral-300 hover:text-white flex items-center gap-1.5 transition-all"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>

            <button
              onClick={handleDownload}
              className="px-3 py-1.5 rounded-xl text-xs font-medium bg-white/5 hover:bg-white/10 border border-white/10 text-neutral-300 hover:text-white flex items-center gap-1.5 transition-all"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export .txt</span>
            </button>

            <button
              onClick={handleCopy}
              className="px-4 py-2 rounded-xl text-xs font-semibold bg-white text-black hover:bg-neutral-200 flex items-center gap-1.5 transition-all shadow-[0_0_15px_rgba(255,255,255,0.2)] active:scale-95"
            >
              {copied ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-600" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy to Clipboard</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
